package com.zcbspay.platform.support.task.pojo;
// default package
// Generated 2017-3-15 11:45:47 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TOrderPaymentDeta generated by hbm2java
 */
@Entity
@Table(name = "T_ORDER_PAYMENT_DETA")
public class OrderPaymentDetaDO implements java.io.Serializable {

	private long tid;
	private Long batchtid;
	private String batchno;
	private String orderid;
	private String currencycode;
	private String amt;
	private String debtorbank;
	private String debtoraccount;
	private String debtorname;
	private String debtorconsign;
	private String creditorbank;
	private String creditoraccount;
	private String creditorname;
	private String proprietary;
	private String summary;
	private String respcode;
	private String respmsg;
	private String relatetradetxn;
	private String status;
	private String notes;
	private String remarks;

	public OrderPaymentDetaDO() {
	}

	public OrderPaymentDetaDO(long tid) {
		this.tid = tid;
	}

	public OrderPaymentDetaDO(long tid, Long batchtid, String batchno,
			String orderid, String currencycode, String amt, String debtorbank,
			String debtoraccount, String debtorname, String debtorconsign,
			String creditorbank, String creditoraccount, String creditorname,
			String proprietary, String summary, String respcode,
			String respmsg, String relatetradetxn, String status, String notes,
			String remarks) {
		this.tid = tid;
		this.batchtid = batchtid;
		this.batchno = batchno;
		this.orderid = orderid;
		this.currencycode = currencycode;
		this.amt = amt;
		this.debtorbank = debtorbank;
		this.debtoraccount = debtoraccount;
		this.debtorname = debtorname;
		this.debtorconsign = debtorconsign;
		this.creditorbank = creditorbank;
		this.creditoraccount = creditoraccount;
		this.creditorname = creditorname;
		this.proprietary = proprietary;
		this.summary = summary;
		this.respcode = respcode;
		this.respmsg = respmsg;
		this.relatetradetxn = relatetradetxn;
		this.status = status;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="seq_order_payment_deta") 
	@SequenceGenerator(name="seq_order_payment_deta",sequenceName="SEQ_ORDER_PAYMENT_DETA",allocationSize=1)
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "BATCHTID", precision = 12, scale = 0)
	public Long getBatchtid() {
		return this.batchtid;
	}

	public void setBatchtid(Long batchtid) {
		this.batchtid = batchtid;
	}

	@Column(name = "BATCHNO", length = 32)
	public String getBatchno() {
		return this.batchno;
	}

	public void setBatchno(String batchno) {
		this.batchno = batchno;
	}

	@Column(name = "ORDERID", length = 32)
	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	@Column(name = "CURRENCYCODE", length = 3)
	public String getCurrencycode() {
		return this.currencycode;
	}

	public void setCurrencycode(String currencycode) {
		this.currencycode = currencycode;
	}

	@Column(name = "AMT", length = 12)
	public String getAmt() {
		return this.amt;
	}

	public void setAmt(String amt) {
		this.amt = amt;
	}

	@Column(name = "DEBTORBANK", length = 14)
	public String getDebtorbank() {
		return this.debtorbank;
	}

	public void setDebtorbank(String debtorbank) {
		this.debtorbank = debtorbank;
	}

	@Column(name = "DEBTORACCOUNT", length = 32)
	public String getDebtoraccount() {
		return this.debtoraccount;
	}

	public void setDebtoraccount(String debtoraccount) {
		this.debtoraccount = debtoraccount;
	}

	@Column(name = "DEBTORNAME", length = 64)
	public String getDebtorname() {
		return this.debtorname;
	}

	public void setDebtorname(String debtorname) {
		this.debtorname = debtorname;
	}

	@Column(name = "DEBTORCONSIGN", length = 60)
	public String getDebtorconsign() {
		return this.debtorconsign;
	}

	public void setDebtorconsign(String debtorconsign) {
		this.debtorconsign = debtorconsign;
	}

	@Column(name = "CREDITORBANK", length = 14)
	public String getCreditorbank() {
		return this.creditorbank;
	}

	public void setCreditorbank(String creditorbank) {
		this.creditorbank = creditorbank;
	}

	@Column(name = "CREDITORACCOUNT", length = 32)
	public String getCreditoraccount() {
		return this.creditoraccount;
	}

	public void setCreditoraccount(String creditoraccount) {
		this.creditoraccount = creditoraccount;
	}

	@Column(name = "CREDITORNAME", length = 64)
	public String getCreditorname() {
		return this.creditorname;
	}

	public void setCreditorname(String creditorname) {
		this.creditorname = creditorname;
	}

	@Column(name = "PROPRIETARY", length = 5)
	public String getProprietary() {
		return this.proprietary;
	}

	public void setProprietary(String proprietary) {
		this.proprietary = proprietary;
	}

	@Column(name = "SUMMARY", length = 64)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "RESPCODE", length = 20)
	public String getRespcode() {
		return this.respcode;
	}

	public void setRespcode(String respcode) {
		this.respcode = respcode;
	}

	@Column(name = "RESPMSG", length = 256)
	public String getRespmsg() {
		return this.respmsg;
	}

	public void setRespmsg(String respmsg) {
		this.respmsg = respmsg;
	}

	@Column(name = "RELATETRADETXN", length = 16)
	public String getRelatetradetxn() {
		return this.relatetradetxn;
	}

	public void setRelatetradetxn(String relatetradetxn) {
		this.relatetradetxn = relatetradetxn;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
