package com.zcbspay.platform.support.order.query.pojo;
// default package
// Generated 2017-3-15 11:45:47 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TOrderCollectBatch generated by hbm2java
 */
@Entity
@Table(name = "T_ORDER_COLLECT_BATCH")
public class OrderCollectBatchDO implements java.io.Serializable {

	private long tid;
	private String version;
	private String accesstype;
	private String coopinstiid;
	private String merid;
	private String encoding;
	private String txntype;
	private String txnsubtype;
	private String biztype;
	private String backurl;
	private String batchno;
	private String txntime;
	private String txndate;
	private Long totalqty;
	private Long totalamt;
	private String reserved;
	private String respcode;
	private String respmsg;
	private String status;
	private String ordercommitime;
	private String orderfinshtime;
	private String syncnotify;
	private String notes;
	private String remarks;
	private String tn;
	public OrderCollectBatchDO() {
	}

	public OrderCollectBatchDO(long tid) {
		this.tid = tid;
	}

	public OrderCollectBatchDO(long tid, String accesstype, String coopinstiid,
			String merid, String encoding, String txntype, String txnsubtype,
			String biztype, String backurl, String batchno, String txntime,
			String txndate, Long totalqty, Long totalamt, String reserved,
			String respcode, String respmsg, String status,
			String ordercommitime, String orderfinshtime, String syncnotify,
			String notes, String remarks) {
		this.tid = tid;
		this.accesstype = accesstype;
		this.coopinstiid = coopinstiid;
		this.merid = merid;
		this.encoding = encoding;
		this.txntype = txntype;
		this.txnsubtype = txnsubtype;
		this.biztype = biztype;
		this.backurl = backurl;
		this.batchno = batchno;
		this.txntime = txntime;
		this.txndate = txndate;
		this.totalqty = totalqty;
		this.totalamt = totalamt;
		this.reserved = reserved;
		this.respcode = respcode;
		this.respmsg = respmsg;
		this.status = status;
		this.ordercommitime = ordercommitime;
		this.orderfinshtime = orderfinshtime;
		this.syncnotify = syncnotify;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="seq_order_collect_batch") 
	@SequenceGenerator(name="seq_order_collect_batch",sequenceName="SEQ_ORDER_COLLECT_BATCH",allocationSize=1)
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	
	@Column(name = "VERSION", length = 6)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "ACCESSTYPE", length = 1)
	public String getAccesstype() {
		return this.accesstype;
	}

	public void setAccesstype(String accesstype) {
		this.accesstype = accesstype;
	}

	@Column(name = "COOPINSTIID", length = 15)
	public String getCoopinstiid() {
		return this.coopinstiid;
	}

	public void setCoopinstiid(String coopinstiid) {
		this.coopinstiid = coopinstiid;
	}

	@Column(name = "MERID", length = 15)
	public String getMerid() {
		return this.merid;
	}

	public void setMerid(String merid) {
		this.merid = merid;
	}

	@Column(name = "ENCODING", length = 2)
	public String getEncoding() {
		return this.encoding;
	}

	public void setEncoding(String encoding) {
		this.encoding = encoding;
	}

	@Column(name = "TXNTYPE", length = 2)
	public String getTxntype() {
		return this.txntype;
	}

	public void setTxntype(String txntype) {
		this.txntype = txntype;
	}

	@Column(name = "TXNSUBTYPE", length = 2)
	public String getTxnsubtype() {
		return this.txnsubtype;
	}

	public void setTxnsubtype(String txnsubtype) {
		this.txnsubtype = txnsubtype;
	}

	@Column(name = "BIZTYPE", length = 6)
	public String getBiztype() {
		return this.biztype;
	}

	public void setBiztype(String biztype) {
		this.biztype = biztype;
	}

	@Column(name = "BACKURL", length = 128)
	public String getBackurl() {
		return this.backurl;
	}

	public void setBackurl(String backurl) {
		this.backurl = backurl;
	}

	@Column(name = "BATCHNO", length = 32)
	public String getBatchno() {
		return this.batchno;
	}

	public void setBatchno(String batchno) {
		this.batchno = batchno;
	}

	@Column(name = "TXNTIME", length = 6)
	public String getTxntime() {
		return this.txntime;
	}

	public void setTxntime(String txntime) {
		this.txntime = txntime;
	}

	@Column(name = "TXNDATE", length = 8)
	public String getTxndate() {
		return this.txndate;
	}

	public void setTxndate(String txndate) {
		this.txndate = txndate;
	}

	@Column(name = "TOTALQTY", precision = 12, scale = 0)
	public Long getTotalqty() {
		return this.totalqty;
	}

	public void setTotalqty(Long totalqty) {
		this.totalqty = totalqty;
	}

	@Column(name = "TOTALAMT", precision = 12, scale = 0)
	public Long getTotalamt() {
		return this.totalamt;
	}

	public void setTotalamt(Long totalamt) {
		this.totalamt = totalamt;
	}

	@Column(name = "RESERVED", length = 1024)
	public String getReserved() {
		return this.reserved;
	}

	public void setReserved(String reserved) {
		this.reserved = reserved;
	}

	@Column(name = "RESPCODE", length = 4)
	public String getRespcode() {
		return this.respcode;
	}

	public void setRespcode(String respcode) {
		this.respcode = respcode;
	}

	@Column(name = "RESPMSG", length = 256)
	public String getRespmsg() {
		return this.respmsg;
	}

	public void setRespmsg(String respmsg) {
		this.respmsg = respmsg;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "ORDERCOMMITIME", length = 14)
	public String getOrdercommitime() {
		return this.ordercommitime;
	}

	public void setOrdercommitime(String ordercommitime) {
		this.ordercommitime = ordercommitime;
	}

	@Column(name = "ORDERFINSHTIME", length = 14)
	public String getOrderfinshtime() {
		return this.orderfinshtime;
	}

	public void setOrderfinshtime(String orderfinshtime) {
		this.orderfinshtime = orderfinshtime;
	}

	@Column(name = "SYNCNOTIFY", length = 2)
	public String getSyncnotify() {
		return this.syncnotify;
	}

	public void setSyncnotify(String syncnotify) {
		this.syncnotify = syncnotify;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	
	@Column(name = "TN", length = 32)
	public String getTn() {
		return this.tn;
	}

	public void setTn(String tn) {
		this.tn = tn;
	}
}
